[package]
name = "bench-piscina"
version = "0.1.0"
edition = "2021"

[build]
target-dir = "Target"

[dependencies]
hyperfine = { version = "1.19.0" }
unbug = { version = "0.4.0", features = ["enable"] }

[[bin]]
name = "Build"
path = "build.rs"

[features]
default = []
Debug = ["unbug/enable"]
